### ISSUE TITLE
[BUG] Service pack exclusion is not fully excluding the service pack

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#146]
**Describe the bug**
I have a configuration file that only has the Kubernetes service pack included in it. The code is also trying to run the storage accounts service pack and so is failing because I don't have the "Azure location" set.

**To Reproduce**
Use the following config.yml and run Probr

```
# Empty and omitted keys will use default values
AuditEnabled: true
AuditDir: audit_output
CucumberDir: cucumber_output
OverwriteHistoricalAudits: true
ServicePacks:
  Kubernetes:
    KubeConfig: /root/.kube/config
    KubeContext:
    ProbeImage: citihub/probr-probe:latest
    AuthorisedContainerRegistry: %AZURE_REGISTRY%
    UnauthorisedContainerRegistry: docker.io
    Probes: # allows this pack's probes to be disabled by name
      - Name: container_registry_access
        Excluded: false
        Justification: "demo"
      - Name: general
        Excluded: false
        Justification: "demo"
      - Name: iam
        Excluded: false
        Justification: "demo"
      - Name: internet_access
        Excluded: false
        Justification: "demo"
      - Name: pod_security_policy
        Excluded: false
        Justification: "demo"
CloudProviders:
  Azure:
    TenantID:
    SubscriptionID:
    ClientID:
    ClientSecret:
    ManagementGroup:
    Location:
    Identity:
      DefaultNamespaceAI:
      DefaultNamespaceAIB:
Tags: # allows user to create their own string of tag inclusions and/or exclusions
TagExclusions: # allows specific controls/scenarios to be disabled via a list of tags
```

Run Probr. It fails with the following error:

`Environment variable "AZURE_LOCATION" is not defined`

However, the Kubernetes service pack doesn't use the Azure provider so it should be ignored.

**Expected behavior**
Probr just runs the Kubernetes service pack.

**Screenshots**
n/a

**Additional context**
We can't break a running pipeline every time we add a new service pack.

**Comment by simonwoolhouse** [comment]
Currently, a service pack has to be explicitly excluded, or it will run
As a temporary fix, you can add the following to the config.yml file under ServicePacks:
  Storage:
     Excluded: "not required"

**Comment by iantivey** [comment]
It still fails with the same error message.  Here's the config I'm using now:

```
# Empty and omitted keys will use default values
AuditEnabled: true
AuditDir: audit_output
CucumberDir: cucumber_output
OverwriteHistoricalAudits: true
ServicePacks:
  Kubernetes:
    KubeConfig: /root/.kube/config
    KubeContext:
    ProbeImage: citihub/probr-probe:latest
    AuthorisedContainerRegistry: %AZURE_REGISTRY%
    UnauthorisedContainerRegistry: docker.io
    Probes: # allows this pack's probes to be disabled by name
      - Name: container_registry_access
        Excluded: false
        Justification: "demo"
      - Name: general
        Excluded: false
        Justification: "demo"
      - Name: iam
        Excluded: false
        Justification: "demo"
      - Name: internet_access
        Excluded: false
        Justification: "demo"
      - Name: pod_security_policy
        Excluded: false
        Justification: "demo"
  Storage:
    Excluded: "only have AKS" #"justification" # any non-empty value here will exclude all elements within the service pack
    Probes: # allows this pack's probes to be disabled by name
      - Name: access_whitelisting
        Excluded:
      - Name: encryption_in_flight
        Scenarios: # allows this probe's scenarios to be disabled using their probe tag value
        - Name: "1.1"
          Excluded:
CloudProviders:
  Azure:
    TenantID:
    SubscriptionID:
    ClientID:
    ClientSecret:
    ManagementGroup:
    Location:
    Identity:
      DefaultNamespaceAI:
      DefaultNamespaceAIB:
Tags: # allows user to create their own string of tag inclusions and/or exclusions
TagExclusions: # allows specific controls/scenarios to be disabled via a list of tags
```
