### ISSUE TITLE
[FEATURE] Tag management configuration

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#16]
**Is your feature request related to a problem? Please describe.**
Currently Probr does not feature a reliable way to skip select events or probes.

**Describe the solution you'd like**
Add a config that allows nesting values for excluding events or probes. This system should replace the default "tags" system. Finally, all exclusions should require a "justification" field.

**Describe alternatives you've considered**
A variety of options were discussed, foremost being to leave the current tag system in place.

**Additional context**
Modify the `tests: tags: ""` config logic to something like the following:

```
events:
    <event tag name>:
        excluded: <true/false>
        justification: <custom string>
        probes: <warn & ignore if event excluded=true>
            <probe tag name>:
                excluded: <true/false>
                justification: <custom string>
```

Check values before event and before scenario. Log configuration into summary accordingly
