### ISSUE TITLE
[FEATURE] Revise config var file handling

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#91]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like the option to exclude service packs, probes, or scenarios individually.

**Describe the solution you'd like**
```
# config.yml  
Exclusions:
  - Name: kubernetes
    Excluded: false
    Justification: "demo"
    Probes:
      - Name: general
        Excluded: false
        Justification: "demo"
        Scenarios:
          - Name: ???
            Excluded: true
            Justification: "demo"
```

**Describe alternatives you've considered**

**Additional context**
