### ISSUE TITLE
[FEATURE] Re-factor configuration file

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#96]
**Is your feature request related to a problem? Please describe.**
The service pack configuration isn't fully contained under "Service Pack"

**Describe the solution you'd like**
```
ServicePacks:
   Kubernetes:
    Excluded: string
    KubeConfig: string
    KubeContext: string
    AuthorisedContainerRegistries: list<string>
    UnauthorisedContainerRegistries: list<string>
    ProbeRegistry: string
    ProbeImage: string
    Probes: list<Probe>
  StorageAccounts:
    Excluded: string
    Specific: string
    Pack: string    
    Config: string
    Probes: list<Probr>
  AnotherService:
    Excluded: string
    Specific: string
    Pack: string    
    Config: string
    Probes: list<Probr>
```

**Additional context**
As we add more service packs we need to make them as self contained as possible
