### ISSUE TITLE
[FEATURE] Probe specific configuration should be part of the "Probe" configuration object

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#98]
**Is your feature request related to a problem? Please describe.**
In the spirit of making the configuration contextually correct, any configuration that is specific to an individual probe should be part of the `Probe` object.  For example
`CloudProviders ->Azure -> Identity -> DefaultNamespaceXX` configuration are specific to the `ServicePack -> Kubernetes -> Probes -> Name: iam` probe.

**Describe the solution you'd like**
Configuration items should be scoped to the object they belong to.

**Comment by eddie-knight** [comment]
This config:
```
CloudProviders:
    Azure:
        Identity:
            DefaultNamespaceAIB: <value>
```

Should be moved out of `CloudProviders` and into the k8s service pack config.
